services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    tty: true
    container_name: app-${PROJECT_NAME}
    ports:
      - "3000:3000"
      - "4000:4000"
    volumes:
      - .:/app
      - ./volumes/logs:/app/logs
      - ./volumes/storage:/app/src/storage
      - ./volumes/nextjs_cache:/app/client/.next # add this to prevent hot reload on next.js when node code is edited.
    networks:
      - cmsnetwork
    depends_on:
      - redis
      - mongo

  redis:
    image: redis:alpine
    container_name: redis-${PROJECT_NAME}
    ports:
      - "6379:6379"
    networks:
      - cmsnetwork
    volumes:
      - ./volumes/redis:/data

  mongo:
    image: mongo:latest
    container_name: mongo-${PROJECT_NAME}
    tty: true
    ports:
      - "27017:27017"
    networks:
      - cmsnetwork
    volumes:
      - ./volumes/mongo:/data/db

networks:
  cmsnetwork:
        driver: bridge