services:
  app:
    container_name: app-${PROJECT_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    privileged: true
    user: root
    tty: true
    ports:
      - 3000:3000
      - 4000:4000
    volumes:
      - .:/app
      - ./volumes/logs:/app/logs
      - ./volumes/storage:/app/src/storage
      - ./volumes/nextjs_cache:/app/client/.next # add this to prevent hot reload on next.js when node code is edited.
    networks:
      - cmsnetwork
    depends_on:
      - redis
      - mongo
    command:
      - make
      - prod

  redis:
    container_name: redis-${PROJECT_NAME}
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - cmsnetwork
    volumes:
      - ./volumes/redis:/data

  mongo:
    container_name: mongo-${PROJECT_NAME}
    image: mongo:latest
    tty: true
    ports:
      - 27017:27017
    networks:
      - cmsnetwork
    volumes:
      - ./volumes/mongo:/data/db

networks:
  cmsnetwork:
    driver: bridge