version: '3.7'

services:
  mongodb_container:
    container_name: mongodb_container
    image: mongo:latest
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: Ham11Bur11
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    restart: always
  redis_container:
    container_name: redis_container
    image: redis:latest
    ports:
      - 6379:6379
    restart: always

volumes:
  mongodb_data_container: