services:
  app:
    image: denoland/deno:latest
    container_name: app-${PROJECT_NAME}
#    build:
#      context: .
#      dockerfile: Dockerfile
    working_dir: /app
    privileged: true
    user: root
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ../:/app
      - ../volumes/logs:/app/logs
      - ../volumes/storage:/app/src/storage
      - ../volumes/nextjs_cache:/app/client/.next # add this to prevent hot reload on next.js when node code is edited.
    networks:
      - cmsnetwork
    command:
      - sleep
      - infinity

networks:
  cmsnetwork:
    driver: bridge