import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "@/components/footer.component";
import React, { PropsWithChildren, ReactNode } from "react";
import { Navbar } from '@/components/navbar.component';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: PropsWithChildren<{ header?: ReactNode; footer?: boolean }>) {
  return (
    <html lang='en'>
      <Navbar />
      <main className="bg-bg1">
        {children}
      </main>
      <Footer />
    </html>
  );
}