import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { Navbar } from '@/components/ui/navbar.component';
import type { NavbarRouteTypes } from '@/components/ui/navbar.component';
import { cn } from '@/lib/utils';
import { ThemeProvider } from '@/components/theme-provider';

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})
const Routes: NavbarRouteTypes[] = [
  {
    path: '',
    name: 'Home'
  },
  {
    path: 'showcase',
    name: 'Showcase Banget'
  }
]

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar routes={Routes} />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}