# create for me docker-compose for redis, mongo, rabbitmq
version: '3.7'

services:
  redis:
    image: redis:alpine
    container_name: redis-cms-app
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  mongo:
    image: mongo:latest
    container_name: mongo-cms-app
    ports:
      - "27017:27017"
    networks:
      - mynetwork

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-cms-app
    ports:
      - "5672:5672"
      # - "15672:15672"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
